### PR TITLE
Feature/78 ruff docstring formatting

### LINKED ISSUE #78: Convert docstrings to Sphinx style
Part of #17 (unless unnecessary, see linked issue for more details)

### PR DESCRIPTION
**Pull request by Mark2000**
## Description
Closes #78 
Closes #94 - duplicates work in that PR

Adds ruff formatting rules for docstrings in envs/general_satellite_tasking. Will roll out to other parts of repo after refactoring of environments into general env. Note that a fairly new ruff>=0.1.9 is required for some features.

How should this pull request be reviewed?
- [ ] By commit
- [X] All changes at once

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Tests still pass.

- [x] __Unit tests__ (General Environment only) `pytest --cov bsk_rl/envs/general_satellite_tasking --cov-report term-missing tests/unittest`
- [x] __Integrated tests__ (General Environment only) `pytest --cov bsk_rl/envs/general_satellite_tasking --cov-report term-missing tests/integration`

### Test Configuration
 - Python: 3.10.11
-  Basilisk: 2.2.2
 - Platform: MacOS

# Checklist:

- [X] My code follows the style guidelines of this project (passes Black, ruff, and isort)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] Commit messages are atomic, are in the form `Issue #XXX: Message` and have a useful message
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Mark2000** [comment]
Let me know if you think the scope should be bigger than just the general env

**Comment by LorenzzoQM** [comment]
I believe limiting the scope for the general environment for now is enough - it is what we are mainly using.

**Review by LorenzzoQM — APPROVED** [review]
Excellent changes to the repo!

**Comment by Mark2000** [comment]
Also working on configuration for #98 , should have some decent documentation generation soon.

**Pull request merged**
